### ISSUE TITLE
ibm-db 3.2.4 breaks ibm-db-django

### ISSUE THREAD

**Issue by lsmoker** [ibmdb/python-ibmdb-django#105]
when ibm-db 3.2.4 is installed, ibm-db-django never returns any rows

**Comment by praveen-db2** [comment]
@lsmoker Recently ibm_db did following change https://github.com/ibmdb/python-ibmdb/pull/971, its been tested as well.  

Can you give a sample program to reproduce this ? It will help to us narrow down issue.

**Comment by imavo** [comment]
Possible duplicate of https://github.com/ibmdb/python-ibmdb/issues/981
Possible regression in the 3.2.4 version of file ibm_db_dbi.py

**Comment by bimalkjha** [comment]
ibm_db=="3.2.5" released with fix of this issue. Hence, closing it. Please verify and update. Thanks.
