### ISSUE TITLE
GeoDjango adapter

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#11]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
GeoDjango (http://docs.djangoproject.com/en/dev/ref/contrib/gis/) is very 
attractive standard Django contrib app. 

Currently IBM DB2 is not supported by GeoDjango. 

DB2 has support for GIS for more than 10 years (DB2 Spatial extender), and is 
free-of-charge: "you can take advantage of the DB2 Spatial Extender free of 
charge in all DB2 editions, including DB2 Express-C."
http://www.ibm.com/developerworks/data/library/techarticle/dm-1006db2expressc972
/index.html

Fast analysis of existing backend implementations gives impression that 
implementing DB2 GeoDjango backend shouldn't be too complex, but for sure it is 
not simple. 
```

Original issue reported on code.google.com by `trebor74hr@gmail.com` on 3 Sep 2010 at 3:23

_Copied from original issue: ibmdb/python-ibmdb#60_

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
GeoDjango backend implementations can be viewed from here 
http://code.djangoproject.com/browser/django/trunk/django/contrib/gis/db/backend
s .
```

Original comment by `trebor74hr@gmail.com` on 3 Sep 2010 at 3:24

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
We didn't get any customer request for this. Once Antonio Cangiano himself 
suggested for this.

```

Original comment by `rahul.pr...@in.ibm.com` on 8 Sep 2010 at 4:23
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

Original comment by `rahul.pr...@in.ibm.com` on 8 Sep 2010 at 4:23

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
Any progress on that ticket? Is there a chance that this will get implemented 
soon?
```

Original comment by `mr.udan...@gmail.com` on 3 Mar 2011 at 6:16

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
Currently we didn't start working on this ticket. 

For which database(DB2/Informix) you wants to use GeoDjango?
```

Original comment by `rahul.pr...@in.ibm.com` on 7 Mar 2011 at 2:47

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:48_

```
I wanted to use DB2 and django with jython. But I just discovered that there is 
no geodjango support for jython yet :/

I think I'll have to check other options.
```

Original comment by `mr.udan...@gmail.com` on 8 Mar 2011 at 8:51

**Comment by hemlatabhatt** [comment]
Please raise a request if its still required ,Closing this for now.
