### ISSUE TITLE
Tested on Ubuntu Linux 7.04 64 bit?

### ISSUE THREAD

**Issue by Stihotvor** [ibmdb/python-ibmdb-django#32]
Please, test the package on a fresh system or correct the readme file.

**Comment by hemlatabhatt** [comment]
@Stihotvor ,Thanks a lot for your inputs ,I am working on the same.Will update the ReadMe file post testing on Newer version Ubuntu System.

**Comment by praveen-db2** [comment]
Will Close this as we had already released support for Django 3.2 and updated Readme file accordingly.
