### ISSUE TITLE
Migration does not work for ManyToMany field with through table.

### ISSUE THREAD

**Issue by Spajderix** [ibmdb/python-ibmdb-django#35]
ManyToMany field will work without issues, but when intermediate model is specified via through option, the resulting model will not migrate.

Python 3.4.8
DB2 V11.1
Django        2.0.9  
ibm-db        2.0.8a0
ibm-db-django 1.2.0.0

**Comment by Vyshakh18** [comment]
@Spajderix Are you still facing this issue?

**Comment by praveen-db2** [comment]
Its working with support for Django 2.2 and 3.1. Hence closing this.
