### ISSUE TITLE
Add support for SSL in ibm-db-django

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#4]
_From @Jamstah on February 23, 2016 17:43_

I need to be able to connect my django application to a DB2 database that is using SSL security.

_Copied from original issue: ibmdb/python-ibmdb#202_

**Comment by kadler** [comment]
_From @Jamstah on February 24, 2016 13:55_

On investigation, there is a workaround here. I'm not sure if its on purpose or not. If you specify a dsn in OPTIONS it gets merged into the kwargs that are given to connect, so you can override the DSN

``` python
DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'DB',
        'USER': 'application',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '50000',
        'OPTIONS': {
            'dsn': 'DATABASE=DB;HOSTNAME=localhost;PORT=50001;PROTOCOL=TCPIP;SECURITY=SSL;SSLCLIENTKEYSTOREDB=/path/to/db2client.kdb;SSLCLIENTKEYSTASH=/path/to/db2client.sth;'
        }
    }
}
```

Its a workaround not a solution, but will keep me going for now.

**Comment by kadler** [comment]
_From @Davin-IBM on May 18, 2017 13:7_

I need this functionality to be supported as well.  +1

**Comment by hemlatabhatt** [comment]
Hi,

I have added the support for SSL from settings file.Please revert in case of any issues .Closing this for now.

Regards
Hemlata
