### ISSUE TITLE
Is ibm_db_django abandoned?

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb-django#49]
At present date May 2020,  with no updates to ibm_db_django since 2018, no support for Django 3, or issues with newer versions of Python, the question needs to be asked:  **Is  ibm_db_django now abandoned?**

**Comment by praveen-db2** [comment]
Hi, sorry for delayed reply. No we have not abandoned  ibm_db_django, its development to support latest versions of Django is going on from past 3 months., you can expect support for Django2.2 in another quarter and 3.0 after 2 more months.

**Comment by carltongibson** [comment]
Thanks for the update. We're looking at the list of third-party backends now, and were wondering about the status.

**Comment by praveen-db2** [comment]
Closing this as we support for latest Django 2.2 and 3.1, shortly we release support for 3.2 as well.

**Comment by carltongibson** [comment]
Super thanks for the update @praveen-db2.
