### ISSUE TITLE
Add ability to specify a schema name

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#5]
_From @mjlawrence83 on November 5, 2015 17:4_

At the moment, when using Django, the schema name must be the same as the user name. I have a scenario where a current legacy database has a schema name that is different from the user name, could the functionality be added to specify a schema name in the Django settings.py file?

_Copied from original issue: ibmdb/python-ibmdb#192_

**Comment by hemlatabhatt** [comment]
Hi,

 I have added the support of the same from settings file.Please revert back in case of any issues .Closing this for now.

Regards
Hemlata
