### ISSUE TITLE
Django 3.0 reports ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by trebor74hr** [ibmdb/python-ibmdb-django#50]
I have problem with django 3.0 modules ibm_db_django/pybase.py" and ibm_db_django/schemaEditor.py report:
`
ImportError: cannot import name 'six' from 'django.utils' (django/utils/__init__.py)
`

Since django.utils.six is [deprected in django 3.0 ](https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils) the fix I found working is:

- intall six: `pip install six`
- change in pybase and schemaEditor.py
```
-    from django.utils import six
==>
+    try:
+        from django.utils import six
+    except ImportError:
+        import six
```

Related tickets:
- https://github.com/ibmdb/python-ibmdb-django/issues/46
- https://github.com/ibmdb/python-ibmdb-django/issues/49

**Comment by praveen-db2** [comment]
Closing this as its already supported in Django 2.2 and 3.1
