### ISSUE TITLE
Operation error in query annotation

### ISSUE THREAD

**Issue by jstenz** [ibmdb/python-ibmdb-django#52]
In this example : `SomeModel.objects.annotate(test=F('field1') / (F('field1') + F('field2')))`
the '+' is swapped with a '-' in the sql request for no apparent reason causing erroneous result.

I committed a solution at [https://github.com/ibmdb/python-ibmdb-django/pull/51](url) if it help.

**Comment by praveen-db2** [comment]
I hope this would be working in Django 2.2 and Django 3.1 supported adapters. Request to reopen if you still find this issue.
