### ISSUE TITLE
Getting error while doing all the steps given in readme.md

### ISSUE THREAD

**Issue by mudittripathi** [ibmdb/python-ibmdb-django#56]
Error says

django.core.exceptions.ImproperlyConfigured: 'ibm_db_django' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by franpss** [comment]
Hi, were you able to solve this? I have the same problem and I haven't been able to solve it. Thanks

**Comment by mudittripathi** [comment]
Yes, I was able to solve this to some extent. Are you using django app to connect?

**Comment by franpss** [comment]
Yes, I made a new Django project exactly like the steps given on readme.md
Thanks for your reply

**Comment by reddibhatini** [comment]
@mudittripathi 
Can you post your versions of 
1. Python (Python --version)
2.Django (Pip list)
3. ibm-db-django (pip list)

I tried different version combos of python, Django, ibm-db-django but couldn't make django, db2 connection work.

**Comment by praveen-db2** [comment]
@mudittripathi @franpss  Are you still facing this issue? I had updated readme. Will be closing this issue, now, if you still persist issue, please feel free to re-open the issue.
