### ISSUE TITLE
South integration

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#6]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
Please provide support for South migrations.
This feature will be soon integrated into Django 1.7 by default.
All the best.
```

Original issue reported on code.google.com by `marcdebu...@gmail.com` on 15 May 2014 at 9:46

_Copied from original issue: ibmdb/python-ibmdb#153_

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
The work for schema migration support for Djano-1.7.x already started... next 
release of ibm_db_django will include this.
```

Original comment by `rahul.pr...@in.ibm.com` on 15 May 2014 at 12:50

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
That's a great news. Do you have any date plan for this release?
```

Original comment by `marcdebu...@gmail.com` on 15 May 2014 at 1:09

**Comment by hemlatabhatt** [comment]
Closing this as syncdb is deprecated in Django ,Re-open is required
