### ISSUE TITLE
django db2 ssl connection

### ISSUE THREAD

**Issue by reddibhatini** [ibmdb/python-ibmdb-django#60]
How would I make django to use ssl connection to db2(sslConnection=true). What options I need to pass to DATBASES dict in settings.py file?
 

BTW, I use this jdbc string in a sql query tool to connect to db2
jdbc:db2://hostname/db_name:sslConnection=true;

**Comment by praveen-db2** [comment]
Hi, I hadn't tried SSL yet, but u can try setting it in settings.py like below.
```

'default': {
        'ENGINE'     : 'ibm_db_django',
        'NAME'       : 'school',
        'USER'       : 'db2admin',
        'PASSWORD'   : 'LNdatabase#1',
        'HOST'       : 'localhost',
        'PORT'       : '50000',
        'security'    : 'ssl',
        'sslservercertificate' : 'fvtserver.arm'
    }, 
```

If it didnt work let me know, i ill work on that when I am free.
