### ISSUE TITLE
Django inspectdb?

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb-django#7]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
When running $ python manage.py inspectdb with a DB2 instance, the output is 
blank. No models are created.

Is inspectdb not implemented? Or is this a bug?

Thanks
```

Original issue reported on code.google.com by `spencer....@gmail.com` on 14 Nov 2013 at 10:09

_Copied from original issue: ibmdb/python-ibmdb#142_

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
Are you seeing this issue with remote connection of AS400? 
This is working fine with DB2 LUW.

```

Original comment by `rahul.pr...@in.ibm.com` on 20 Nov 2013 at 7:18

**Comment by kadler** [comment]
_From @GoogleCodeExporter on March 16, 2015 6:50_

```
Yes, I should have mentioned that. This issue is with the AS400 connection.
```

Original comment by `spencer....@gmail.com` on 20 Nov 2013 at 1:10

**Comment by Vyshakh18** [comment]
Could you try modifying ibm_db_django/ibm_db_django/operations.py in the quote_name 
function to not put quotes around the table name, and check if this would help? - this may not be the final solution, but just a workaround until the fix is available.

**Comment by eliz-pri** [comment]
Has this issue been fixed?

**Comment by hemlatabhatt** [comment]
@eliz-pri  ,i am working on this .

**Comment by hemlatabhatt** [comment]
@eliz-pri  ,I have merged the code for the inspectdb support.Please let me know if you are facing any issues.Closing this for now.

**Comment by bansanguy** [comment]
Wrt the above issue resolution, can you tell me which version the code has been merged with?

**Comment by SabaKauser** [comment]
as of today, the code is available only in git. it would be released to pypi sometime later. 
Hence, current source in git has the resolution.

**Comment by SabaKauser** [comment]
the PR used it his https://github.com/ibmdb/python-ibmdb-django/pull/18
for django 2.0 support.
