### ISSUE TITLE
Testcase  for Django Version x.x

### ISSUE THREAD

**Issue by dkdndes** [ibmdb/python-ibmdb-django#71]
Django has by now Version 4.0, could you provide a test case for the DB2 connection, which checks the version or tell me how to check it?

**Comment by praveen-db2** [comment]
@dkdndes you can use below statement in any test case,
` from django import VERSION as djangoVersion`
    
Value in object djangoVersion will be like, Ex: (3, 2, 11, 'alpha', 0)
You can use this object directly in your work.

Otherwise you can also use below code ex:
```
    from django import get_version
    from django import VERSION as djangoVersion
    def test_development(self):        
        ver_string = get_version(djangoVersion)
```

**Comment by praveen-db2** [comment]
@dkdndes can we close this issue ? Did my sample code help you ?

**Comment by dkdndes** [comment]
Thank you @praveen-db2
