### ISSUE TITLE
Django compatibility

### ISSUE THREAD

**Issue by wandss** [ibmdb/python-ibmdb-django#76]
Is ibm-db-django compatible with Django 4?

**Comment by bimalkjha** [comment]
@wandss No. It works till version 3.2 only. It is clearly documented. Check the prerequisite section here: https://github.com/ibmdb/python-ibmdb-django#prerequisites-for-django-on-python
Thanks.

**Comment by 0x2ec** [comment]
Just to follow up on this, is there any desire to support Django 4?

**Comment by 0x2ec** [comment]
Oh, I just found #80 that mentions that Django 4.x should work, just ignore me.

**Comment by mattixpet** [comment]
@0x2ec your point is still valid. Support for 4.2 would be great since 3.2 is end of support from Django in april 2024. That #80 is still open and unmerged.
