### ISSUE TITLE
Inspect DB

### ISSUE THREAD

**Issue by wandss** [ibmdb/python-ibmdb-django#77]
Hello. I'm trying to inspect a Database using mange.py inspectdb, but this database has a schema name different than the username.
Is there any option, right of bat "replace" the schema name?

Right now I'm thinking of having a custom command, but not sure if this would be the best approach.

Thanks.

**Comment by praveen-db2** [comment]
@wandss  please refer https://www.ibm.com/docs/en/db2/11.5?topic=statements-set-schema

**Comment by wandss** [comment]
Hello @praveen-db2 
Thanks. After reading the source code at the ibm_db_django packages I saw at some python module that it checked for the "CURRENTSCHEMA" key inside DATABASES on the django settings.
So after setting that, all good.

Thanks again.
Great work!
