### ISSUE TITLE
Informix Support

### ISSUE THREAD

**Issue by andrewvillano** [ibmdb/python-ibmdb-django#87]
I reached this page from the IBM Documentation that shows support for Informix v11+, https://www.ibm.com/docs/en/db2/9.7?topic=applications-python-sqlalchemy-django-framework

Latest version of the same document:
https://www.ibm.com/docs/en/db2/11.5?topic=applications-python-sqlalchemy-django-framework

I have setup my Informix 14.x.x instance to use DRDA, which is the DB2 communication protocol. 

The ibm-db python library supports informix, and I am able to extract data, however when I use ibm-db-django and run `python manage.py inspectdb` it returns an empty schema:

```
[andrew@villano-vm myproj]$ python manage.py inspectdb
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
[andrew@villano-vm myproj]$ 
```

Is there something I am missing?

Thanks.

**Comment by praveen-db2** [comment]
@andrewvillano 
1. You need to add inspectdb under INSTALLED_APPS in setting.py file.
2. you need to run below
   "django-admin.py makemigrations inspectdb --settings=settings"
   "django-admin.py migrate --setting=settings inspectdb"
   "./runtests.py --settings=settings inspectdb"

**Comment by praveen-db2** [comment]
@andrewvillano were you able to resolve this ?

**Comment by andrewvillano** [comment]
No

Mr. Andrew V. Villano, CCNA, RHCSA
Linux Systems Engineer
United States District Court
Theodore Roosevelt United States Courthouse
225 Cadman Plaza East, Room 304S
Brooklyn, NY 11201-1818
(718) 613 - 2682
***@***.***
________________________________

**Comment by praveen-db2** [comment]
@andrewvillano try running like "python manage.py test inspectdb"
If not worked, send me contents of your settings.py file.

**Comment by praveen-db2** [comment]
Closing this as no response from user.
