### ISSUE TITLE
STOP using apache license 😠🧐

### ISSUE THREAD

**Issue by tavo-wasd-gh** [ibmdb/python-ibmdb-django#94]
License under GNU GPL v3
Apache is a permissive open license, **please** license this program with a proper **FREE** as in **FREEDOM** license.

1. 'COPYING' file at project root with the GPL license [text](https://www.gnu.org/licenses/gpl-3.0.txt).
2. Copyright notice along the lines of "_Copyright © 2023 John Doe_" at the top of every file.
3. Right afer the notice, append the following copying permission statement:

> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

> You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

STOP big tech from stealing your code, make use of your rights to FREEEEDoOOOMMMMMM.

**Comment by bimalkjha** [comment]
@tavo-wasd-gh Thanks for the suggestion. We'll evaluate it in consultation of our legal team and update the license accordingly if required. Thanks.
